const { Dish } = require("../models");

const dishdata = [
  {
    name: "Opela",
    price: 20,
    description: "et tempus semper est",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 6,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Sonsing",
    price: 25,
    description: "libero non mattis pulvinar nulla pede ullamcorper",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 15,
    picture_id: "smorgasbord/dish4",
  },
  {
    name: "Domainer",
    price: 19,
    description: "sapien quis libero nullam",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 6,
    picture_id: "smorgasbord/dish2",
  },
  {
    name: "Bitchip",
    price: 25,
    description: "quam nec dui luctus rutrum nulla tellus",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 9,
    picture_id: "smorgasbord/dish2",
  },
  {
    name: "Aerified",
    price: 9,
    description: "at nunc commodo placerat",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 2,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Span",
    price: 16,
    description: "curae donec pharetra magna vestibulum",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 4,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Konklux",
    price: 6,
    description: "eu interdum eu",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 8,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Ventosanzap",
    price: 16,
    description: "enim in tempor turpis nec euismod",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 1,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Fixflex",
    price: 18,
    description: "et magnis dis parturient montes nascetur ridiculus",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 11,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Matsoft",
    price: 24,
    description: "cursus id turpis integer aliquet massa",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 1,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Cardguard",
    price: 12,
    description: "quis libero nullam sit amet turpis",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 10,
    picture_id: "smorgasbord/dish4",
  },
  {
    name: "Treeflex",
    price: 24,
    description: "faucibus cursus urna ut tellus",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 3,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Hatity",
    price: 11,
    description: "eu interdum eu tincidunt in",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 15,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Otcom",
    price: 20,
    description: "duis faucibus accumsan odio curabitur",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 13,
    picture_id: "smorgasbord/dish4",
  },
  {
    name: "Cardify",
    price: 9,
    description: "cursus id turpis",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 9,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Bitchip",
    price: 17,
    description: "faucibus orci luctus et ultrices",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 7,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Viva",
    price: 13,
    description: "penatibus et magnis dis parturient montes nascetur",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 15,
    picture_id: "smorgasbord/dish4",
  },
  {
    name: "Quo Lux",
    price: 25,
    description: "ipsum primis in faucibus orci",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 2,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Ventosanzap",
    price: 13,
    description: "dictumst aliquam augue quam sollicitudin vitae consectetuer",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 7,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Home Ing",
    price: 21,
    description: "aliquam lacus morbi quis tortor",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 11,
    picture_id: "smorgasbord/dish4",
  },
  {
    name: "Veribet",
    price: 5,
    description: "cubilia curae duis faucibus accumsan",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 4,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Hatity",
    price: 18,
    description: "duis at velit eu est congue elementum",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 15,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Tres-Zap",
    price: 7,
    description: "habitasse platea dictumst",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 8,
    picture_id: "smorgasbord/dish4",
  },
  {
    name: "Fix San",
    price: 18,
    description: "integer aliquet massa id lobortis convallis",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 15,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Gembucket",
    price: 15,
    description: "pretium quis lectus suspendisse",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 5,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Domainer",
    price: 6,
    description: "eu mi nulla",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 2,
    picture_id: "smorgasbord/dish2",
  },
  {
    name: "Lotstring",
    price: 21,
    description: "semper porta volutpat quam pede",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 1,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Daltfresh",
    price: 13,
    description: "nec nisi volutpat eleifend",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 10,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Stim",
    price: 12,
    description: "non lectus aliquam sit",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 14,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "It",
    price: 14,
    description: "sapien a libero nam dui",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 6,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Span",
    price: 17,
    description: "augue vestibulum ante ipsum primis in faucibus",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 10,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Subin",
    price: 11,
    description: "ligula nec sem duis aliquam convallis nunc",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 10,
    picture_id: "smorgasbord/dish4",
  },
  {
    name: "Bytecard",
    price: 9,
    description: "diam id ornare imperdiet sapien",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 11,
    picture_id: "smorgasbord/dish2",
  },
  {
    name: "Trippledex",
    price: 11,
    description: "donec dapibus duis at",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 8,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Duobam",
    price: 14,
    description: "nisi vulputate nonummy maecenas tincidunt",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 3,
    picture_id: "smorgasbord/dish2",
  },
  {
    name: "Bitchip",
    price: 10,
    description: "odio cras mi",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 4,
    picture_id: "smorgasbord/dish2",
  },
  {
    name: "Zathin",
    price: 9,
    description: "platea dictumst maecenas ut massa quis augue",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 11,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Transcof",
    price: 15,
    description: "lacus purus aliquet at",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 8,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Tampflex",
    price: 7,
    description: "ipsum aliquam non",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 4,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Lotlux",
    price: 17,
    description: "diam vitae quam",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 13,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Keylex",
    price: 14,
    description: "nam tristique tortor eu pede",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 14,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Alpha",
    price: 18,
    description: "ipsum ac tellus semper interdum",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 11,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Tres-Zap",
    price: 19,
    description: "fusce lacus purus aliquet at feugiat non",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 11,
    picture_id: "smorgasbord/dish2",
  },
  {
    name: "Vagram",
    price: 25,
    description: "curae donec pharetra magna",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 14,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Holdlamis",
    price: 11,
    description: "cras mi pede malesuada in",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 8,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Bytecard",
    price: 20,
    description: "eleifend donec ut dolor morbi vel",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 12,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Greenlam",
    price: 16,
    description: "sem duis aliquam convallis nunc proin at",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 9,
    picture_id: "smorgasbord/dish4",
  },
  {
    name: "Subin",
    price: 23,
    description: "congue elementum in",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 12,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Lotlux",
    price: 16,
    description: "metus sapien ut nunc vestibulum",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 4,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Konklab",
    price: 5,
    description: "consequat morbi a ipsum integer",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 15,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Bitchip",
    price: 7,
    description: "aenean auctor gravida sem",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 9,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Lotstring",
    price: 21,
    description: "in felis eu",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 5,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Konklux",
    price: 9,
    description: "cras pellentesque volutpat dui maecenas tristique est",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 14,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Cookley",
    price: 21,
    description: "sapien dignissim vestibulum vestibulum ante ipsum",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 6,
    picture_id: "smorgasbord/dish2",
  },
  {
    name: "Tempsoft",
    price: 22,
    description: "volutpat eleifend donec",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 1,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Biodex",
    price: 8,
    description: "porttitor pede justo eu massa donec dapibus",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 10,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Rank",
    price: 16,
    description: "purus sit amet nulla",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 8,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Bitwolf",
    price: 22,
    description: "posuere cubilia curae mauris",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 1,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Gembucket",
    price: 10,
    description: "ipsum primis in faucibus orci",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 15,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Pannier",
    price: 17,
    description: "sit amet eros suspendisse accumsan tortor",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 8,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Gembucket",
    price: 10,
    description: "nam congue risus",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 3,
    picture_id: "smorgasbord/dish2",
  },
  {
    name: "Greenlam",
    price: 21,
    description: "scelerisque quam turpis",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 6,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Temp",
    price: 20,
    description: "elit proin risus praesent lectus vestibulum quam",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 4,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Viva",
    price: 13,
    description: "nec nisi vulputate nonummy",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 6,
    picture_id: "smorgasbord/dish4",
  },
  {
    name: "Voltsillam",
    price: 10,
    description: "donec semper sapien a",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 1,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Stringtough",
    price: 24,
    description: "mattis egestas metus aenean fermentum",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 5,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Tresom",
    price: 13,
    description: "eu mi nulla ac enim in",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 14,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Domainer",
    price: 12,
    description: "a odio in hac habitasse platea dictumst",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 7,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Temp",
    price: 21,
    description: "molestie hendrerit at",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 10,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Otcom",
    price: 11,
    description: "quam pharetra magna ac consequat",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 3,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Hatity",
    price: 9,
    description: "mus vivamus vestibulum sagittis sapien cum sociis",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 10,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Cardguard",
    price: 25,
    description: "justo lacinia eget tincidunt eget tempus",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 7,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Y-Solowarm",
    price: 15,
    description: "venenatis turpis enim blandit",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 13,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Zaam-Dox",
    price: 18,
    description: "dolor quis odio consequat varius integer ac",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 7,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Kanlam",
    price: 21,
    description: "ligula nec sem",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 12,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Mat Lam Tam",
    price: 14,
    description: "etiam pretium iaculis justo in hac",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 12,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Bigtax",
    price: 24,
    description: "eget tempus vel",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 14,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Bigtax",
    price: 18,
    description: "placerat ante nulla",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 5,
    picture_id: "smorgasbord/dish4",
  },
  {
    name: "Zaam-Dox",
    price: 23,
    description: "auctor sed tristique in tempus",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 8,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Redhold",
    price: 22,
    description: "nonummy maecenas tincidunt lacus at velit",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 9,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Ronstring",
    price: 12,
    description: "integer non velit",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 1,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Flexidy",
    price: 17,
    description: "nonummy integer non velit donec diam",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 9,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Regrant",
    price: 21,
    description: "odio cras mi",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 5,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Bytecard",
    price: 5,
    description: "ligula suspendisse ornare consequat",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 3,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Andalax",
    price: 5,
    description: "a pede posuere nonummy integer non velit",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 14,
    picture_id: "smorgasbord/dish4",
  },
  {
    name: "Tin",
    price: 23,
    description: "magna vestibulum aliquet ultrices erat tortor sollicitudin",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 9,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Alpha",
    price: 15,
    description: "sit amet lobortis sapien",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 11,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Fix San",
    price: 23,
    description: "luctus tincidunt nulla mollis",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 10,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Biodex",
    price: 12,
    description: "sed sagittis nam congue risus",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 7,
    picture_id: "smorgasbord/dish5",
  },
  {
    name: "Cardify",
    price: 25,
    description: "hac habitasse platea dictumst aliquam augue quam",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 15,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Tin",
    price: 19,
    description: "sed tristique in tempus sit amet",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 12,
    picture_id: "smorgasbord/dish4",
  },
  {
    name: "Y-find",
    price: 6,
    description: "justo eu massa donec dapibus duis",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 13,
    picture_id: "smorgasbord/dish1",
  },
  {
    name: "Zathin",
    price: 17,
    description: "quis augue luctus tincidunt nulla",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 7,
    picture_id: "smorgasbord/dish2",
  },
  {
    name: "Hatity",
    price: 25,
    description: "lectus pellentesque at",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 15,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Temp",
    price: 24,
    description: "magna at nunc",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 9,
    picture_id: "smorgasbord/dish4",
  },
  {
    name: "Wrapsafe",
    price: 25,
    description: "donec diam neque vestibulum eget",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 14,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Andalax",
    price: 9,
    description: "tortor duis mattis egestas metus aenean",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 2,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Flexidy",
    price: 15,
    description: "vel augue vestibulum rutrum rutrum neque",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 7,
    picture_id: "smorgasbord/dish6",
  },
  {
    name: "Keylex",
    price: 21,
    description: "aliquam non mauris morbi non lectus",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 12,
    picture_id: "smorgasbord/dish3",
  },
  {
    name: "Bitchip",
    price: 9,
    description: "in hac habitasse platea",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 11,
    picture_id: "smorgasbord/dish2",
  },
];

const seedDishes = () => Dish.bulkCreate(dishdata, { individualHooks: true });

module.exports = seedDishes;
