const { Dish } = require("../models");

const dishdata = [
  {
    name: "justo pellentesque",
    price: 32,
    description: "tortor quis turpis sed ante",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 1,
  },
  {
    name: "iaculis",
    price: 18,
    description: "adipiscing elit proin risus praesent lectus",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 7,
  },
  {
    name: "orci pede",
    price: 6,
    description: "justo nec condimentum neque sapien placerat ante nulla justo",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 10,
  },
  {
    name: "pretium quis",
    price: 8,
    description: "erat quisque erat eros viverra eget congue eget",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 15,
  },
  {
    name: "sed",
    price: 25,
    description: "quam turpis adipiscing lorem vitae mattis",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 2,
  },
  {
    name: "quam turpis",
    price: 31,
    description:
      "eleifend quam a odio in hac habitasse platea dictumst maecenas",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 13,
  },
  {
    name: "dui",
    price: 16,
    description: "nisl duis ac nibh fusce lacus purus aliquet",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 5,
  },
  {
    name: "integer",
    price: 15,
    description: "non interdum in ante vestibulum ante ipsum primis",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 9,
  },
  {
    name: "orci",
    price: 37,
    description: "nisl duis ac nibh fusce lacus purus",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 11,
  },
  {
    name: "felis ut",
    price: 23,
    description: "eu felis fusce posuere felis sed lacus morbi sem mauris",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 7,
  },
  {
    name: "sapien",
    price: 30,
    description: "sagittis dui vel nisl duis ac nibh fusce lacus purus",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 8,
  },
  {
    name: "rhoncus",
    price: 15,
    description: "non quam nec dui luctus",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 1,
  },
  {
    name: "volutpat erat",
    price: 23,
    description: "feugiat non pretium quis lectus suspendisse",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 10,
  },
  {
    name: "sociis natoque",
    price: 21,
    description: "at turpis a pede posuere nonummy integer non",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 15,
  },
  {
    name: "arcu",
    price: 13,
    description:
      "justo nec condimentum neque sapien placerat ante nulla justo aliquam",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 3,
  },
  {
    name: "vestibulum sagittis",
    price: 18,
    description: "pede venenatis non sodales sed tincidunt eu felis fusce",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 2,
  },
  {
    name: "nunc",
    price: 16,
    description: "sed justo pellentesque viverra pede ac diam cras",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 7,
  },
  {
    name: "at velit",
    price: 16,
    description: "nulla nisl nunc nisl duis",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 11,
  },
  {
    name: "nam tristique",
    price: 5,
    description: "sed nisl nunc rhoncus dui vel sem sed sagittis",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 2,
  },
  {
    name: "amet",
    price: 11,
    description: "tristique est et tempus semper est quam pharetra magna ac",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 7,
  },
  {
    name: "vestibulum",
    price: 13,
    description: "maecenas ut massa quis augue luctus tincidunt nulla",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 5,
  },
  {
    name: "sit",
    price: 32,
    description:
      "nam nulla integer pede justo lacinia eget tincidunt eget tempus",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 1,
  },
  {
    name: "nisl venenatis",
    price: 38,
    description: "suscipit a feugiat et eros vestibulum",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 7,
  },
  {
    name: "massa volutpat",
    price: 35,
    description: "cursus id turpis integer aliquet",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 5,
  },
  {
    name: "platea dictumst",
    price: 22,
    description:
      "posuere cubilia curae mauris viverra diam vitae quam suspendisse",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 3,
  },
  {
    name: "sed justo",
    price: 7,
    description: "nunc nisl duis bibendum felis sed interdum venenatis",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 6,
  },
  {
    name: "at",
    price: 12,
    description: "nec dui luctus rutrum nulla tellus",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 4,
  },
  {
    name: "odio elementum",
    price: 28,
    description: "odio porttitor id consequat in",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 3,
  },
  {
    name: "quam",
    price: 35,
    description:
      "suspendisse potenti nullam porttitor lacus at turpis donec posuere metus",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 5,
  },
  {
    name: "nisl",
    price: 38,
    description: "lacus purus aliquet at feugiat non pretium quis lectus",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 10,
  },
  {
    name: "erat",
    price: 28,
    description: "morbi non lectus aliquam sit amet diam in",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 5,
  },
  {
    name: "sed nisl",
    price: 22,
    description: "turpis enim blandit mi in porttitor",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 10,
  },
  {
    name: "in",
    price: 5,
    description: "consequat nulla nisl nunc nisl duis",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 4,
  },
  {
    name: "volutpat erat",
    price: 7,
    description: "tortor sollicitudin mi sit amet lobortis sapien sapien non",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 15,
  },
  {
    name: "vitae",
    price: 10,
    description: "tortor sollicitudin mi sit amet lobortis sapien sapien non",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 13,
  },
  {
    name: "et tempus",
    price: 25,
    description: "adipiscing lorem vitae mattis nibh ligula",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 3,
  },
  {
    name: "sem",
    price: 31,
    description:
      "ipsum primis in faucibus orci luctus et ultrices posuere cubilia",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 4,
  },
  {
    name: "diam",
    price: 28,
    description: "erat tortor sollicitudin mi sit amet lobortis",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 2,
  },
  {
    name: "et commodo",
    price: 10,
    description: "massa tempor convallis nulla neque libero convallis eget",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 12,
  },
  {
    name: "tincidunt",
    price: 14,
    description:
      "iaculis diam erat fermentum justo nec condimentum neque sapien",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 6,
  },
  {
    name: "maecenas",
    price: 11,
    description: "ante ipsum primis in faucibus orci luctus et",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 10,
  },
  {
    name: "rutrum rutrum",
    price: 15,
    description: "sapien cursus vestibulum proin eu mi nulla ac enim",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 14,
  },
  {
    name: "eu magna",
    price: 19,
    description: "rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 3,
  },
  {
    name: "eget",
    price: 11,
    description: "lectus in est risus auctor",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 8,
  },
  {
    name: "aenean",
    price: 19,
    description:
      "odio cras mi pede malesuada in imperdiet et commodo vulputate",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 8,
  },
  {
    name: "accumsan tellus",
    price: 38,
    description: "quam suspendisse potenti nullam porttitor lacus at",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 3,
  },
  {
    name: "sed",
    price: 35,
    description: "vestibulum sit amet cursus id turpis integer aliquet",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 6,
  },
  {
    name: "odio curabitur",
    price: 34,
    description: "sem sed sagittis nam congue risus semper",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 10,
  },
  {
    name: "sit amet",
    price: 40,
    description: "in quis justo maecenas rhoncus aliquam lacus morbi",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 3,
  },
  {
    name: "quisque",
    price: 35,
    description: "ultrices posuere cubilia curae duis faucibus",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 4,
  },
  {
    name: "nisl",
    price: 37,
    description: "ultrices posuere cubilia curae duis faucibus accumsan odio",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 14,
  },
  {
    name: "non",
    price: 26,
    description:
      "purus aliquet at feugiat non pretium quis lectus suspendisse potenti",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 2,
  },
  {
    name: "et eros",
    price: 29,
    description: "sit amet lobortis sapien sapien non mi integer ac",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 14,
  },
  {
    name: "non",
    price: 33,
    description: "vitae mattis nibh ligula nec sem duis aliquam convallis",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 2,
  },
  {
    name: "id",
    price: 8,
    description: "interdum eu tincidunt in leo maecenas pulvinar",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 6,
  },
  {
    name: "libero",
    price: 17,
    description: "mus etiam vel augue vestibulum rutrum",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 8,
  },
  {
    name: "et magnis",
    price: 19,
    description: "eros elementum pellentesque quisque porta volutpat erat",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 5,
  },
  {
    name: "nisl duis",
    price: 10,
    description: "curabitur in libero ut massa volutpat convallis morbi",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 14,
  },
  {
    name: "arcu libero",
    price: 19,
    description: "sapien urna pretium nisl ut volutpat",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 1,
  },
  {
    name: "aenean",
    price: 9,
    description: "venenatis non sodales sed tincidunt eu felis fusce posuere",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 11,
  },
  {
    name: "amet cursus",
    price: 25,
    description: "platea dictumst maecenas ut massa quis augue luctus",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 4,
  },
  {
    name: "quam nec",
    price: 8,
    description: "tincidunt eu felis fusce posuere felis sed lacus morbi",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 15,
  },
  {
    name: "libero convallis",
    price: 21,
    description: "tristique fusce congue diam id ornare imperdiet sapien urna",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 4,
  },
  {
    name: "vel sem",
    price: 31,
    description: "porttitor lacus at turpis donec posuere metus vitae ipsum",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 10,
  },
  {
    name: "quam",
    price: 34,
    description: "non mauris morbi non lectus aliquam",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 8,
  },
  {
    name: "eros",
    price: 9,
    description: "lectus pellentesque eget nunc donec",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 5,
  },
  {
    name: "maecenas",
    price: 39,
    description: "porttitor id consequat in consequat ut",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 4,
  },
  {
    name: "at",
    price: 13,
    description: "interdum eu tincidunt in leo maecenas pulvinar lobortis est",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 11,
  },
  {
    name: "ut odio",
    price: 12,
    description: "tristique in tempus sit amet sem fusce",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 14,
  },
  {
    name: "sapien",
    price: 14,
    description: "cras in purus eu magna vulputate luctus cum",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 15,
  },
  {
    name: "sit",
    price: 25,
    description: "nisl nunc rhoncus dui vel",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 4,
  },
  {
    name: "rutrum",
    price: 40,
    description: "neque vestibulum eget vulputate ut ultrices",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 14,
  },
  {
    name: "sed",
    price: 19,
    description: "nunc purus phasellus in felis donec",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 10,
  },
  {
    name: "semper est",
    price: 13,
    description: "aenean fermentum donec ut mauris",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 12,
  },
  {
    name: "lectus",
    price: 21,
    description: "molestie sed justo pellentesque viverra pede ac",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 7,
  },
  {
    name: "vulputate luctus",
    price: 14,
    description:
      "at lorem integer tincidunt ante vel ipsum praesent blandit lacinia",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 11,
  },
  {
    name: "at ipsum",
    price: 26,
    description: "pharetra magna ac consequat metus sapien",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 4,
  },
  {
    name: "amet sapien",
    price: 30,
    description: "nulla eget eros elementum pellentesque",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 1,
  },
  {
    name: "pulvinar",
    price: 6,
    description:
      "massa volutpat convallis morbi odio odio elementum eu interdum",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 15,
  },
  {
    name: "pede",
    price: 31,
    description: "non mi integer ac neque",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 10,
  },
  {
    name: "ultrices",
    price: 24,
    description: "morbi porttitor lorem id ligula",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 4,
  },
  {
    name: "amet eros",
    price: 22,
    description: "rhoncus aliquam lacus morbi quis tortor id",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 6,
  },
  {
    name: "nisi vulputate",
    price: 32,
    description: "ultrices vel augue vestibulum ante",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 7,
  },
  {
    name: "augue",
    price: 38,
    description: "in quis justo maecenas rhoncus aliquam lacus morbi",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 15,
  },
  {
    name: "lectus in",
    price: 31,
    description: "aliquet massa id lobortis convallis tortor",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 8,
  },
  {
    name: "turpis integer",
    price: 33,
    description: "massa id lobortis convallis tortor risus dapibus",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 15,
  },
  {
    name: "posuere",
    price: 36,
    description:
      "vivamus tortor duis mattis egestas metus aenean fermentum donec ut",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 4,
  },
  {
    name: "maecenas pulvinar",
    price: 40,
    description: "est et tempus semper est quam",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 4,
  },
  {
    name: "lectus",
    price: 6,
    description: "phasellus sit amet erat nulla tempus vivamus in",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 5,
  },
  {
    name: "magnis dis",
    price: 7,
    description: "cubilia curae mauris viverra diam vitae quam suspendisse",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 10,
  },
  {
    name: "mauris non",
    price: 31,
    description: "potenti nullam porttitor lacus at turpis",
    vegetarian: true,
    gluten_free: false,
    restaurant_id: 10,
  },
  {
    name: "curae duis",
    price: 19,
    description: "cum sociis natoque penatibus et magnis dis",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 2,
  },
  {
    name: "lectus",
    price: 15,
    description: "vivamus vel nulla eget eros elementum pellentesque",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 8,
  },
  {
    name: "consequat varius",
    price: 30,
    description: "vestibulum ante ipsum primis in faucibus orci luctus et",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 5,
  },
  {
    name: "vestibulum",
    price: 29,
    description: "pellentesque at nulla suspendisse potenti cras in purus eu",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 7,
  },
  {
    name: "neque",
    price: 11,
    description: "amet nunc viverra dapibus nulla suscipit ligula in lacus",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 3,
  },
  {
    name: "erat",
    price: 34,
    description: "proin leo odio porttitor id consequat in consequat",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 2,
  },
  {
    name: "sit amet",
    price: 18,
    description: "penatibus et magnis dis parturient montes nascetur ridiculus",
    vegetarian: false,
    gluten_free: true,
    restaurant_id: 7,
  },
  {
    name: "accumsan",
    price: 40,
    description:
      "erat id mauris vulputate elementum nullam varius nulla facilisi",
    vegetarian: true,
    gluten_free: true,
    restaurant_id: 12,
  },
  {
    name: "magna at",
    price: 34,
    description: "in est risus auctor sed tristique in tempus sit",
    vegetarian: false,
    gluten_free: false,
    restaurant_id: 10,
  },
];

const seedDishes = () => Dish.bulkCreate(dishdata, { individualHooks: true });

module.exports = seedDishes;
